permalink: /:year-:month-:day/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: ":num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      styles : [highlight.css,post.css]
      scripts : [post.js]



title: "Essential singularity"
email: "miccots@gmail.com"
description: ""
github_username:  "mkotsur"
swiftype_searchId: "ncwR9a8S9CTx2q9SgsJm"
disqus_shortname: "mkotsur"




url: "http://127.0.0.1:4000/"
imgrepo: "https://mkotsur.github.io/static/img"


#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

# Gems
gems: [jekyll-paginate]
